---
- name: Opening Firewall Ports - RPM
  block:
    - name: Open Minecraft Server Port on Firewall
      firewalld:
        port: "{{ minecraft_server_port }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes

    - name: Open Minecraft Query Port on Firewall
      firewalld:
        port: "{{ minecraft_query_port }}/udp"
        permanent: yes
        state: enabled
        immediate: yes

    - name: Open Minecraft RCON Port on Firewall
      firewalld:
        port: "{{ rcon_port }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes
  when: ansible_os_family == "RedHat"

- name: Opening Firewall Ports - DPKG
  block:
    - name: Open Minecraft Server Port on Firewall
      ufw:
        port: "{{ minecraft_server_port }}"
        rule: allow
        proto: tcp

    - name: Open Minecraft Query Port on Firewall
      ufw:
        port: "{{ minecraft_query_port }}"
        rule: allow
        proto: udp

    - name: Open Minecraft RCON Port on Firewall
      ufw:
        port: "{{ rcon_port }}"
        rule: allow
        proto: tcp
  when: ansible_os_family == "Debian"
